workflows:
  # Expo iOS Build with EAS
  expo-ios-eas:
    name: Demo_App iOS Build
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN # Add this as environment variable in Codemagic dashboard
        BUNDLE_ID: "com.pcamocardi.demoapp"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd Demo_App
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Login to EAS
        script: |
          cd Demo_App
          eas login --non-interactive --token $EXPO_TOKEN
      - name: Build iOS with EAS
        script: |
          cd Demo_App
          eas build --platform ios --profile development --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true

  # Expo Web Build
  expo-web-simple:
    name: Demo_App Web Build
    max_build_duration: 30
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          cd Demo_App
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Build web app
        script: |
          cd Demo_App
          npx expo export --platform web
    artifacts:
      - Demo_App/dist/**/*
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true

  # React Native iOS Build (Main App)
  react-native-ios:
    name: Calculator App iOS Build
    max_build_duration: 60
    environment:
      vars:
        BUNDLE_ID: "com.pcamocardi.demoapp"
        XCODE_WORKSPACE: "ios/Demo_app.xcworkspace"
        XCODE_SCHEME: "Demo_app"
        XCODE_PROJECT: "ios/Demo_app.xcodeproj"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.app
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true