workflows:
  # Expo Development Build
  expo-development:
    name: Demo_App Development Build
    max_build_duration: 45
    environment:
      groups:
        - expo
      vars:
        BUNDLE_ID: "com.pcamocardi.demoapp"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install expo-dev-client
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Set up EAS authentication and build
        script: |
          # Make sure EAS CLI uses your token
          export EXPO_TOKEN=$EXPO_TOKEN
          # Verify login
          npx eas whoami
          # Build iOS app (credentials will be managed automatically)
          npx eas build -p ios --profile development --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true

  # Expo Web Build
  expo-web:
    name: Demo_App Web Build
    max_build_duration: 30
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install expo-dev-client
      - name: Install Expo CLI
        script: |
          npm install -g @expo/cli
      - name: Build web app
        script: |
          npx expo export --platform web
    artifacts:
      - dist/**/*
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true

  # Expo Production Build (Basic)
  expo-production-basic:
    name: Demo_App Production Build
    max_build_duration: 60
    environment:
      groups:
        - expo
      vars:
        BUNDLE_ID: "com.pcamocardi.demoapp"
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install expo-dev-client
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Set up EAS authentication and build
        script: |
          # Make sure EAS CLI uses your token
          export EXPO_TOKEN=$EXPO_TOKEN
          # Verify login
          npx eas whoami
          # Build iOS app
          npx eas build -p ios --profile production --non-interactive
    artifacts:
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - pcamocardi@example.com # Replace with your email
        notify:
          success: true
          failure: true